site_name: Coppafish Documentation
repo_url: https://github.com/reillytilbury/coppafish
theme:

  name: material
  features:
    - navigation.tabs
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      scheme: slate
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
nav:
  - Getting started: index.md
  - Basic usage: basic_usage.md
  - Glossary: glossary.md
