site_name: Coppafish Documentation
repo_url: https://github.com/reillytilbury/coppafish

theme:
  name: material
  logo: images/logo.svg

  features:
    # Cool section selection at top
    - navigation.tabs
    # Code blocks
    - content.code.annotation
    # Copy code button
    - content.code.copy
  
  language: en

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      scheme: slate
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Getting started: index.md
  - Usage: basic_usage.md
  - Method: method.md
  - Diagnostics: diagnostics.md
  - Glossary: glossary.md

# This part allows mathematics to be displayed LaTeX style, by using $...$ for in line or $$...$$ for multi-line.
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  # Footnote support
  - footnotes
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
