site_name: Coppafish Documentation
repo_url: https://github.com/paulshuker/coppafish

theme:
  name: material
  logo: images/logo.svg

  features:
    # Cool section selection at top (sticky makes tabs stay shown when scrolling)
    - navigation.tabs
    - navigation.tabs.sticky
    # Code blocks
    - content.code.annotation
    # Copy code button
    - content.code.copy
  
  language: en

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      scheme: slate
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Getting started: index.md
  - Usage:
    - Basic Usage: basic_usage.md
    - Advanced Usage: advanced_usage.md
  - Overview: overview.md
  - Method:
    - Stitch: stitch.md
    - Registration: register.md
    - Call Spots: call_spots.md
    - OMP: omp.md
  - Diagnostics: diagnostics.md
  - Troubleshoot: troubleshoot.md
  - Glossary: glossary.md
  - Contributing: contributing.md

# This part allows mathematics to be displayed LaTeX style, by using $...$ for in line or $$...$$ for multi-line.
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  # Code can be highlighted, for example python code by code block: ``` python ...``` or inline: `#!python ...`.
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  # Footnote support
  - footnotes
  # Captions and aligned images support
  - md_in_html
  # Re-sizeable images
  - attr_list

# Required for LaTeX maths support.
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
