[tool.pytest.ini_options]
markers = [
    "manual: tests only run manually",
    "integration: integration tests",
]
# Create a code coverage report at the end of pytest using the package pytest-cov.
# It seems that debugging is not possible with this option enabled. See the following link for more information:
# https://github.com/microsoft/vscode-python/issues/693
# comment out the following line to enable debugging.
#addopts = "--cov=coppafish --cov-report term"

[tool.black]
line-length = 120

[tool.pyright]
typeCheckingMode = "off"
# Fix relative importing resolves using pyright.
executionEnvironments = {"root" = "src"}

