[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: integration tests",
]
# Create a code coverage report at the end of pytest using the package pytest-cov.
addopts = "--cov=coppafish --cov-report term"

[tool.black]
line-length = 120

[tool.pyright]
typeCheckingMode = "off"
# Fix relative importing resolves using pyright.
executionEnvironments = {"root" = "src"}
