[tool.black]
line-length = 120

[tool.isort]
profile = "black"
filter_files = true
line_length = 120

[tool.pyright]
typeCheckingMode = "off"
exclude = [ "**/temp", "temp.py", "**/__pycache__", "**/build/lib" ]
