[tool.black]
line-length = 120

[tool.isort]
profile = "black"
filter_files = true

[tool.pyright]
typeCheckingMode = "off"
# Fix relative importing resolves using pyright.
include = ["src" ]
exclude = [ "**/temp", "temp.py", "**/__pycache__", "**/build/lib" ]
executionEnvironments = [
    { "root" = "src" },
]
