[tool.black]
line-length = 120

[tool.isort]
profile = "black"
filter_files = true
line_length = 120

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
exclude = [ "**/temp", "temp.py", "**/__pycache__", "**/build/lib" ]
ignore = ["E741"]
