name: Unit Tests

# Trigger on any push or pull requests
on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      # Do not fail fast, so we can see all errors from the unit/integration tests
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.9"
          - "3.10"
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install pytest
        run: python -m pip install pytest

      - name: Install non-jax dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install .
      
      - name: Run non-jax unit tests
        run: pytest -m 'not slow and not optimised and not integration'

      - name: Install jax dependencies
        run: |
          python -m pip install -r requirements-optimised.txt
          python -m pip install .[optimised]

      - name: Run jax unit tests
        run: pytest -m 'not slow and not integration'

      - name: Run jax integration tests
        run: pytest -m 'integration and not slow'
