name: CI

# Trigger on any push or pull requests.
on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache pip dependencies.
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          # Cache the pip cache directory based on the hash of the requirements files
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt', '**/requirements-torch.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install default dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-torch.txt

      - name: Install coppafish
        run: python -m pip install .

      - name: Verify coppafish import
        run: python -Ic "import coppafish"

      - name: Install dev packages
        run: python -m pip install -r requirements-dev.txt

      - name: Check pre-commit hooks
        run: |
          pre-commit autoupdate
          pre-commit run --all-files --show-diff-on-failure
        continue-on-error: false

      - name: Lint checks
        run: pyright .
        continue-on-error: false

      - name: Run default unit tests
        run: pytest -m "not integration and not notebook" --cov=coppafish --cov-report term

      - name: Run default integration tests
        run: pytest -m "integration" --cov=coppafish --cov-report term

      - name: Run notebook-dependent tests
        run: pytest -m "notebook" --cov=coppafish --cov-report term
