name: CI

# Trigger on any push or pull requests
on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      # Do not fail fast, so we can see all errors from the unit/integration tests
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.9"
          - "3.10"
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install pytest
        run: python -m pip install pytest

      - name: Install pytorch dependencies
        run: python -m pip install -r requirements-pytorch.txt

      - name: Install coppafish[pytorch]
        run: python -m pip install .[pytorch]

      - name: Run pytorch unit tests
        run: pytest -m 'pytorch and not slow'
